dist: xenial
cache: bundler
language: ruby
install:
  - 'gem update --system'
  - 'gem --version'
  - 'gem install bundler -v 2.0.1'
  - 'bundle --version'
  - bundle
rvm:
  - 2.4.1
  - 2.5
  - 2.6
  - ruby-head
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libavahi-compat-libdnssd-dev libsodium
  homebrew:
    packages:
      - libsodium
notifications:
  email: false
